city/urls.py
from django.urls import path

from city.views import index

app_name = "city"

urlpatterns = [
    path('', index, name='index'),

]

city_hall/urls.py
from django.urls import path

from city_hall.views import index

app_name = "city_hall"

urlpatterns = [
    path('', index, name='index'),

]

company/urls.py
from django.urls import path

from company.views import index

app_name = "company"

urlpatterns = [
    path('', index, name='index'),

]

master/urls.py
from django.urls import path

from master.views import index

app_name = "master"

urlpatterns = [
    path('', index, name='index'),

]

prefecture/urls.py
from django.urls import path

from prefecture.views import index

app_name = "prefecture"

urlpatterns = [
    path('', index, name='index'),

]

user/urls.py
from django.urls import path

from user.views import user_account

app_name = "user"

urlpatterns = [
    path('', user_account, name='index'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

from user.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('user/', include('user.urls', namespace='user')),
    path('company/', include('company.urls', namespace='company')),
    path('prefecture/', include('prefecture.urls', namespace='prefecture')),
    path('master/', include('master.urls', namespace='master')),
    path('city/', include('city.urls', namespace='city')),
    path('city_hall/', include('city_hall.urls', namespace='city_hall')),

]

city/models.py
from django.db import models

# Create your models here.

city_hall/models.py
from django.db import models

# Create your models here.

company/models.py
from django.db import models

# Create your models here.

master/models.py
from django.db import models

# Create your models here.

prefecture/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models

# Create your models here.

city/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'city/lk.html')

city_hall/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'city_hall/lk.html')

company/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'company/lk.html')

master/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'master/lk.html')

prefecture/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'prefecture/lk.html')

user/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'user/welcome.html')


def user_account(request):
    return render(request, 'user/lk.html')

city/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block css %} {% endblock %}
    <title>Title</title>
</head>
<body>

{% block content %}
{% endblock %}

</body>
</html>

city_hall/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block css %} {% endblock %}
    <title>Title</title>
</head>
<body>

{% block content %}
{% endblock %}

</body>
</html>

city_hall/templates/city_hall/lk.html
{% extends 'base.html' %}

{% block content %}
<h1>
    Кабинет мерии
</h1>

<a href="{% url 'user:index' %}">Личный кабинет</a>

{% endblock %}

company/templates/company/lk.html
{% extends 'base.html' %}

{% block content %}
<h1>
    Кабинет Фирмы
</h1>

<a href="{% url 'user:index' %}">Личный кабинет</a>

{% endblock %}

master/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block css %} {% endblock %}
    <title>Title</title>
</head>
<body>

{% block content %}
{% endblock %}

</body>
</html>

master/templates/master/lk.html
{% extends 'base.html' %}

{% block content %}
<h1>
    Кабинет мастера
</h1>

<a href="{% url 'user:index' %}">Личный кабинет</a>

{% endblock %}

prefecture/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block css %} {% endblock %}
    <title>Title</title>
</head>
<body>

{% block content %}
{% endblock %}

</body>
</html>

prefecture/templates/prefecture/lk.html
{% extends 'base.html' %}

{% block content %}
<h1>
    Кабинет Префектуры
</h1>

<a href="{% url 'user:index' %}">Личный кабинет</a>
{% endblock %}

user/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% block css %}
    {% endblock %}
</head>
<body>

{% block content %}
{% endblock %}

</body>
</html>

user/templates/user/lk.html
{% extends 'base.html' %}

{% block content %}
<h1>
    Кабинет пользователя
</h1>
<div style="display: grid;">
    <a href="{% url 'city:index' %}">Кабинет города</a>
    <a href="{% url 'city_hall:index' %}">Кабинет мерии</a>
    <a href="{% url 'master:index' %}">Кабинет мастера</a>
    <a href="{% url 'company:index' %}">Кабинет фирмы</a>
    <a href="{% url 'prefecture:index' %}">Кабинет префектуры</a>
</div>
{% endblock %}

user/templates/user/welcome.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css_files/user/index.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="welcome">
        <a class="link" href="{% url 'user:index' %}">
            Welcome!
        </a>
    </div>
</div>
{% endblock %}